#    Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [4]:
 import numpy as np

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [6]:
N = int(input("Введите число "))
array = np.array([])
while N != 0:
    array = np.append(array, N)
    N = N - 1
print(array)

Введите число 11
[11. 10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
number = int(input("Введите количество элементов в главной диагонали: "))
#Создаём диагональную матрицу от 0 до number - 1
matrix = np.diag(np.arange(number))
#Выводим сумму главной диагонали матрицы
print(sum(np.diag(matrix)))


Введите количество элементов в главной диагонали: 5
10


# Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [19]:
a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b = np.array( [4, 12, -3] )

In [17]:
from numpy import linalg

In [20]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
x / y

array([0.25, 0.4 , 0.5 ])